package com.example.kitchensink.model;

import lombok.*;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/**
 * The Role class represents a role in the system.
 * It is mapped to a MongoDB collection called "roles".
 * A Role object contains an ID (which is automatically generated by MongoDB) and a name (the role name).
 * Lombok annotations are used for generating getters, setters, constructors, equals, hashCode, and toString methods automatically.
 */
@Data   // Lombok annotation to generate getters, setters, equals, hashCode, and toString methods
@NoArgsConstructor  // Lombok annotation to generate a no-args constructor
@AllArgsConstructor // Lombok annotation to generate an all-args constructor
@Document(collection = "roles")  // MongoDB collection mapping for the Role object
public class Role {

    /**
     * The unique identifier for the role.
     * MongoDB uses String as the default type for IDs.
     */
    @Id
    private String id;

    /**
     * The name of the role (e.g., "Admin", "User").
     * This field is used to identify the role in the system.
     */
    private String name;
}
